server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  prefix: /api  # 添加路由前缀
  routes:
    item-service: /item/**  # 将商品微服务映射到/item/**
    search-service: /search/**  # 将搜索微服务映射到/search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    upload-service:
      path: /upload/** # 将文件上传映射到 /upload/**
      serviceId: upload-service
      strip-prefix: false # 去掉前缀
  add-host-header: true # 携带请求本身的 host 头信息
  sensitive-headers:  # 禁用使用的头信息，设置为 null,否则 set-cookie 无效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 3000 # ribbon 连接超时时间(ms)
  ReadTimeout: 3500 # ribbon 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
ly:
  jwt:
    pubKeyPath: D:/leyou/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item